language: php
php:
  - 5.3.3
  - 5.4
branches:
  only:
    - /^7.x/
env:
  - FEDORA_VERSION="3.5"
  - FEDORA_VERSION="3.6.2"
  - FEDORA_VERSION="3.7.0"
before_install:
  - export ISLANDORA_DIR=$TRAVIS_BUILD_DIR
  - $TRAVIS_BUILD_DIR/tests/scripts/travis_setup.sh
  - cd $HOME/drupal-*
script:
  - ant -buildfile sites/all/modules/islandora/build.xml lint
  - $ISLANDORA_DIR/tests/scripts/line_endings.sh sites/all/modules/islandora
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer islandora
  - phpcpd --names *.module,*.inc,*.test sites/all/modules/islandora
  - drush test-run --uri=http://localhost:8081 Islandora
